name: CI

concurrency:
  group: ${{ github.workflow }}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    env:
      # Deal with rate limits on the GitHub API during tests
      EGET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: pnpm
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - run: |
        pnpm install --frozen-lockfile
        pnpm typecheck
      shell: bash
    
  test:
    runs-on: ubuntu-latest
    env:
      # Deal with rate limits on the GitHub API during tests
      EGET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: pnpm
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - run: |
        pnpm install --frozen-lockfile
        pnpm build
        pnpm test
      shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
