name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: pnpm
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - run: pnpm install --frozen-lockfile
    - run: pnpm build
    - run: pnpm test
