name: Test

on:
  push:
    branches: [ master, humphd/node-wrapper ]
  pull_request:
    branches: [ master, humphd/node-wrapper ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # TODO: add more when this works...
        #os: [ubuntu-latest, macos-latest, windows-latest]
        #node-version: [22, 24]
        os: [ubuntu-latest]
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - run: pnpm install --frozen-lockfile
    - run: pnpm build
    - run: pnpm test
